apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: thesis-ingress
spec:
  rules:
  - host: "thesis.new.hua.gr"
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: thesis-clip
            port:
              number: 8080

