apiVersion: apps/v1
kind: Deployment
metadata:
  name: thesis-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: thesis
  template:
    metadata:
      labels:
        component: thesis
    spec:
      containers:
        - name: thesis
          image: 'thesis-app:02021808'
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: thesis-configmap
          env:
            - name: SECRET_COOKIE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysecrets
                  key: secretcookie
            - name: LOGIN_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysecrets
                  key: adminpass
            - name: LDAP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysecrets
                  key: ldappass
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: mysecrets
                  key: miniosecret